#!/usr/bin/env bash
# The test suite for this project, and it runs on BOTH sides of the mirror pair: the private
# working repo where bin/ is edited, and the public mirror where CI is a thin wrapper around
# this same file.
#
#   bash tests/run.sh              every group that can run here
#   bash tests/run.sh T3 T5        just those groups
#
# It touches no network, calls neither Spotify nor YouTube, and commits no audio: the mp3s in
# T4 are generated by ffmpeg into a temp directory and deleted with it.
#
# 🔒 A group that cannot run reports SKIP and is counted in the summary. It is never silently
# a pass. A check that cannot tell "nothing wrong" from "I could not look" is not a check.
#
# ONE FILE, NOT TWO. Four groups are about the code (lint, fresh clone, metadata, gesture) and
# are identical wherever they run. Two are about the published artifact (T2 hygiene, T6 docs)
# and mean nothing in the private repo, where a tracked CLAUDE.md, real paths and a real
# playlists.tsv are all correct. One is about the real library (T7) and there is no library in
# the mirror. Those three SKIP with a reason on the side they do not apply to, rather than
# living in a second file that would drift from this one.
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 1

# Which side of the pair is this? Decided by a file, not a heuristic: .mirror-manifest is the
# private repo's declaration of what may cross, so only the private side carries one. A
# downloader's clone has no manifest and correctly reads as the public artifact.
if [ -f "$ROOT/.mirror-manifest" ]; then SIDE="private"; else SIDE="public"; fi

SHELLCHECK="${SHELLCHECK:-shellcheck}"
PASS=0; FAIL=0; SKIPPED=0
FAILED_NAMES=(); SKIPPED_NAMES=()
TMP=""

# Invoked by the trap below, which shellcheck cannot see. Both codes are needed: 0.10 and
# later call this SC2329, while 0.9 reports the same thing as SC2317, and ubuntu-24.04 ships
# 0.9. Suppressing only the code your own shellcheck emits passes locally and reddens CI.
# shellcheck disable=SC2317,SC2329
cleanup() { [ -n "$TMP" ] && rm -rf "$TMP"; }
trap cleanup EXIT

if [ -t 1 ]; then G=$'\033[32m'; R=$'\033[31m'; Y=$'\033[33m'; B=$'\033[1m'; N=$'\033[0m'
else G=""; R=""; Y=""; B=""; N=""; fi

group() { printf '\n%s%s%s\n' "$B" "$1" "$N"; }
ok()    { PASS=$((PASS+1));    printf '  %sPASS%s  %s\n' "$G" "$N" "$1"; }
bad()   { FAIL=$((FAIL+1)); FAILED_NAMES+=("$1")
          printf '  %sFAIL%s  %s\n' "$R" "$N" "$1"
          [ $# -gt 1 ] && [ -n "$2" ] && printf '%s\n' "$2" | sed 's/^/          /'; }
skip()  { SKIPPED=$((SKIPPED+1)); SKIPPED_NAMES+=("$1 ($2)")
          printf '  %sSKIP%s  %s (%s)\n' "$Y" "$N" "$1" "$2"; }

# assert_empty <name> <text> [hint] : passes when the text is empty. Most hygiene checks are
# greps that must find nothing, and this keeps their reporting identical.
assert_empty() {
  local what="$1" got="$2" hint="${3:-}"
  if [ -z "$got" ]; then ok "$what"; else bad "$what" "${hint:+$hint
}$got"; fi
}

assert_eq() {  # assert_eq <name> <want> <got>
  local what="$1" want="$2" got="$3"
  if [ "$want" = "$got" ]; then ok "$what"; else bad "$what" "want: $want
got:  $got"; fi
}

want_group() {  # no arguments means all of them
  [ ${#WANTED[@]} -eq 0 ] && return 0
  local g; for g in "${WANTED[@]}"; do [ "$g" = "$1" ] && return 0; done
  return 1
}

tracked() { git -C "$ROOT" ls-files 2>/dev/null; }
is_repo()  { git -C "$ROOT" rev-parse --git-dir >/dev/null 2>&1; }

# The files this project ships, by extension. Tracked PLUS untracked-not-ignored, so a script
# written this session is still linted, while a gitignored one is not: bin/env.local.sh is
# machine-specific, has no shebang and is absent from a clone by design, so linting it would
# report three findings that are all correct and none actionable. Outside a checkout (someone
# unpacked a tarball) it falls back to walking the tree and excludes that file by name.
list_files() {  # list_files '\.sh'
  local rx="$1"
  if is_repo; then
    { tracked; git -C "$ROOT" ls-files --others --exclude-standard; } | sort -u | grep -E "$rx\$"
  else
    find . -path ./.git -prune -o -type f -print 2>/dev/null | sed 's|^\./||' \
      | grep -E "$rx\$" | grep -v '^bin/env\.local\.sh$' | sort
  fi
}

# A python that can import mutagen: the spotdl venv on a real install, the system one in CI
# where python3-mutagen is a 1 MB apt package rather than a 400 MB venv.
mutagen_python() {
  local c
  for c in "${SPOTDL_VENV:-$HOME/.local/spotdl-venv}/bin/python" python3; do
    [ -x "$c" ] || c="$(command -v "$c" 2>/dev/null)" || continue
    [ -n "$c" ] || continue
    "$c" -c 'import mutagen' >/dev/null 2>&1 && { printf '%s' "$c"; return 0; }
  done
  return 1
}

# ---------------------------------------------------------------------------
# T1  lint: does every shipped file still parse, and can it be run at all
# ---------------------------------------------------------------------------
t1_lint() {
  group "T1  lint"
  local f out broken=""
  local -a sh_list py_list
  mapfile -t sh_list < <(list_files '\.sh')
  mapfile -t py_list < <(list_files '\.py')
  printf '  ....  linting %s shell and %s python file(s)\n' "${#sh_list[@]}" "${#py_list[@]}"
  if [ "${#sh_list[@]}" -eq 0 ]; then
    bad "there are shell scripts to lint" "found none, which cannot be right. Refusing to report an empty run as clean."
    return
  fi

  # bash -n first, because it needs nothing installed. Even with no shellcheck on the box,
  # a syntax error still fails the suite rather than skipping it.
  for f in "${sh_list[@]}"; do
    out="$(bash -n "$f" 2>&1)" || broken="$broken$f: $out"$'\n'
  done
  assert_empty "every shell script parses (bash -n)" "$broken"

  if command -v "$SHELLCHECK" >/dev/null 2>&1; then
    # -P SCRIPTDIR so `source "$(dirname "$0")/env.sh"` resolves. Without it every caller
    # reports SC1091 "not following", 17 notes that say nothing about the code.
    out="$("$SHELLCHECK" -x -P SCRIPTDIR "${sh_list[@]}" 2>&1)"
    assert_empty "shellcheck clean" "$out"
  else
    skip "shellcheck clean" "shellcheck not installed; set SHELLCHECK=<path> to point at one"
  fi

  broken=""
  for f in "${py_list[@]}"; do
    out="$(python3 -m py_compile "$f" 2>&1)" || broken="$broken$f: $out"$'\n'
  done
  rm -rf bin/__pycache__
  assert_empty "every python file compiles" "$broken"

  broken=""
  for f in "${sh_list[@]}" "${py_list[@]}"; do
    [ -e "$f" ] || continue
    head -c 2 "$f" | grep -q '#!' || broken="$broken$f"$'\n'
    [ -x "$f" ] || broken="$broken$f (not executable)"$'\n'
  done
  assert_empty "every script has a shebang and an exec bit" "$broken" \
    "a clone whose scripts will not run is a bad first impression"

  if is_repo; then
    # The exec bit has to be recorded in git, not just set locally, or it does not survive
    # the clone that is the whole point of this check.
    broken="$(git -C "$ROOT" ls-files -s -- 'bin/*.sh' 'bin/*.py' setup.sh 'tests/*' \
              | awk '$1 != "100755" {print $4" is mode "$1", want 100755"}')"
    assert_empty "the exec bit is recorded in git, not just locally" "$broken"

    broken="$(tracked | while read -r f; do
                [ -f "$f" ] && grep -qU $'\r' "$f" 2>/dev/null && printf '%s\n' "$f"
              done)"
    assert_empty "no CRLF line endings" "$broken"
  else
    skip "git-recorded exec bits and CRLF" "not a git checkout"
  fi
}

# ---------------------------------------------------------------------------
# T2  publishing hygiene: Set B and Set L, mechanised
#
# The pre-push hook checks some of this, but it lives in .git/hooks and a fresh clone comes
# back without it. This runs on GitHub, where it cannot be missing.
# ---------------------------------------------------------------------------
t2_hygiene() {
  group "T2  publishing hygiene"
  if [ "$SIDE" = "private" ]; then
    # Not a weaker check here, a meaningless one. Every rule below is inverted in the private
    # repo: CLAUDE.md is tracked and should be, ~/Claude paths are correct, playlists.tsv is
    # real listening data, and the maintainer's name is ordinary. Running it here would print
    # a wall of failures that say nothing, which is how a suite gets ignored.
    skip "the whole publishing group" "private working repo; these rules describe the published mirror"
    return
  fi
  if ! is_repo; then
    skip "the whole hygiene group" "not a git checkout, so there is no tracked set to audit"
    return
  fi

  # Tracked AND untracked-but-not-ignored, because the second set is what is about to be
  # committed. Auditing only what git already knows about would clear a stray file on exactly
  # the run before it gets published.
  local files; files="$( { tracked; git -C "$ROOT" ls-files --others --exclude-standard; } | sort -u )"
  local count; count="$(printf '%s\n' "$files" | grep -c .)"
  if [ "$count" -eq 0 ]; then
    bad "the file list is readable" "git returned nothing. Refusing to report a zero-file scan as clean."
    return
  fi
  printf '  ....  auditing %s file(s), tracked plus untracked-not-ignored\n' "$count"
  # An array, so a filename with a space stays one pathspec instead of becoming two.
  local -a flist; mapfile -t flist <<< "$files"

  # The allowlist from megaplay/CLAUDE.md. Anything not on it does not publish.
  local strays
  strays="$(printf '%s\n' "$files" | grep -vE '^(bin/|tests/|\.github/|README\.md$|CONTRIBUTING\.md$|LICENSE$|setup\.sh$|playlists\.tsv\.example$|\.gitignore$)')"
  assert_empty "every tracked file is on the allowlist" "$strays" \
    "allowlist: bin/ tests/ .github/ README.md CONTRIBUTING.md LICENSE setup.sh playlists.tsv.example .gitignore"

  # L1. A repo that ships code is a tool; a repo that ships songs is distribution.
  assert_empty "no audio files (Set L1)" \
    "$(printf '%s\n' "$files" | grep -iE '\.(mp3|m4a|flac|wav|ogg|opus|aac|wma|aiff?)$')"

  assert_empty "no library state or machine-specific files" \
    "$(printf '%s\n' "$files" | grep -E '(^|/)(playlists\.tsv|env\.local\.sh)$|(^|/)(\.state|index)/')"

  assert_empty "no planning docs" \
    "$(printf '%s\n' "$files" | grep -iE '(^|/)(CLAUDE|SESSIONS|SCOPE|STATUS|NOTES)\.md$')"

  # ⚠️ Plain grep, NOT `git grep`. git grep searches tracked content only, so a file that is
  # untracked-but-about-to-be-committed would be allowlist-checked above and then skipped by
  # every content check below. That is the exact "passed because I could not look" shape this
  # suite is supposed to prevent, and it was live here until a test clone caught it.
  scan() { grep -nIE "$1" "${flist[@]}" 2>/dev/null; }

  # Private paths. The working copy of bin/ lives in a private repo alongside a real library
  # and a real env.local.sh, and syncs here wholesale, so this is the leak with an actual
  # delivery mechanism behind it.
  # The [~/] and [-] brackets stop the patterns from matching the line they are written on.
  # Same idea as `ps aux | grep [s]shd`, and without it the checker reports itself forever.
  assert_empty "no private paths in published content" \
    "$(scan '/home/[a-z]+/|[~/]Claude/[a-z]|CLAUDE[-]MIRROR')" \
    "derive paths from BASH_SOURCE or __file__, or put them in bin/env.local.sh"

  # The maintainer's name belongs in LICENSE as the copyright holder and nowhere else: not in
  # code, not in comments, not in anything the tool prints while it runs.
  assert_empty "no personal names outside LICENSE" \
    "$(grep -nI '[E]than' -r bin tests .github README.md CONTRIBUTING.md setup.sh 2>/dev/null)"

  # A house rule on everything published under the maintainer's name, and an AI tell besides.
  assert_empty "no long dashes" \
    "$(grep -nIP '[\x{2014}\x{2013}]' "${flist[@]}" 2>/dev/null)"

  # L3. These are spotdl's own shipped anonymous credentials. Swapping in a registered app's
  # would put the project under the Spotify Developer Terms for no benefit.
  local id secret
  id="$(grep -oP '(?<=^SPOTIFY_ID=")[a-f0-9]+' bin/env.sh || true)"
  secret="$(grep -oP '(?<=^SPOTIFY_SECRET=")[a-f0-9]+' bin/env.sh || true)"
  if [ "$id" = "5f573c9620494bae87890c0f08a60293" ] && [ "$secret" = "212476d9b0f3472eaa762d90b19b0ba8" ]; then
    ok "Spotify credentials are still spotdl's own (Set L3)"
  else
    bad "Spotify credentials are still spotdl's own (Set L3)" \
        "env.sh no longer carries spotdl's shipped public credentials. If this is deliberate, read Set L3 in CLAUDE.md before changing this test."
  fi
}

# ---------------------------------------------------------------------------
# T3  a fresh clone, which is the case this whole suite exists for
#
# Copies the shipped tree somewhere else, under a $HOME that has nothing in it and with NO
# bin/env.local.sh, then exercises the shared helpers. The machine this is developed on has an
# env.local.sh and a full library behind it; a downloader has neither.
# ---------------------------------------------------------------------------
t3_fresh_clone() {
  group "T3  fresh clone, no env.local.sh, empty library"
  TMP="${TMP:-$(mktemp -d)}"
  local proj="$TMP/t3/proj" home="$TMP/t3/home" music="$TMP/t3/music"
  mkdir -p "$proj" "$home" "$music"
  cp -r bin "$proj/bin"
  # Both are NATIVE to the mirror and absent from the private repo. bin/ is what this group
  # actually exercises, so their absence changes nothing.
  for f in setup.sh playlists.tsv.example; do [ -e "$f" ] && cp "$f" "$proj/"; done
  rm -f "$proj/bin/env.local.sh"
  rm -rf "$proj/bin/__pycache__"

  local out
  out="$(HOME="$home" MEGAPLAY_MUSIC="$music" SPOTDL_VENV="$home/.local/spotdl-venv" \
         bash -c '
    set -u
    . "'"$proj"'/bin/env.sh"
    printf "PROJECT=%s\n"  "$PROJECT"
    printf "MUSIC=%s\n"    "$MUSIC"
    printf "REGHEAD=%s\n"  "$(head -1 "$REGISTRY" | tr "\t" ",")"

    reg_add "Parent/Sub" "abc123" 130 0
    printf "GET_ID=%s\n"   "$(reg_get "Parent/Sub" playlist_id)"
    reg_set "Parent/Sub" offset 130
    printf "GET_OFF=%s\n"  "$(reg_get "Parent/Sub" offset)"
    printf "NAMES=%s\n"    "$(reg_names | tr "\n" "|")"
    reg_del "Parent/Sub"
    printf "AFTER_DEL=%s\n" "$(reg_names | tr "\n" "|")"

    printf "ARTIST_NESTED=%s\n" "$(artist_of "Parent/Sub")"
    printf "ARTIST_FLAT=%s\n"   "$(artist_of "Solo Playlist")"
    printf "ENT_ALBUM=%s\n"     "$(entity_of "https://open.spotify.com/album/1x2y")"
    printf "ENT_PLAIN=%s\n"     "$(entity_of "37i9dQZF1DX")"
    printf "URL_FROM_ID=%s\n"   "$(spotify_url "37i9dQZF1DX")"
    printf "URL_KEPT=%s\n"      "$(spotify_url "https://open.spotify.com/album/1x2y")"
    printf "ID_FROM_URL=%s\n"   "$(spotify_id "https://open.spotify.com/album/1x2y?si=abc")"
    printf "SLUG=%s\n"          "$(slug "90s Rap/Best Of")"
  ' 2>&1)" || { bad "env.sh sources in a fresh tree" "$out"; return; }

  get() { printf '%s\n' "$out" | sed -n "s/^$1=//p"; }

  assert_eq "PROJECT is derived from BASH_SOURCE, not hardcoded" "$proj"  "$(get PROJECT)"
  assert_eq "MEGAPLAY_MUSIC is honoured"                          "$music" "$(get MUSIC)"
  assert_eq "the registry is created with its header"    "name,playlist_id,cap,offset" "$(get REGHEAD)"
  assert_eq "reg_add then reg_get round-trips"           "abc123" "$(get GET_ID)"
  assert_eq "reg_set updates one column"                 "130"    "$(get GET_OFF)"
  assert_eq "reg_names lists a nested name"              "Parent/Sub|" "$(get NAMES)"
  assert_eq "reg_del removes it"                         ""       "$(get AFTER_DEL)"
  assert_eq "artist_of on a megaplaylist is the parent"  "Parent" "$(get ARTIST_NESTED)"
  assert_eq "artist_of on a flat name is the name"       "Solo Playlist" "$(get ARTIST_FLAT)"
  assert_eq "an album URL reads as an album"             "album"  "$(get ENT_ALBUM)"
  assert_eq "a bare id reads as a playlist"              "playlist" "$(get ENT_PLAIN)"
  assert_eq "spotify_url builds a playlist URL from an id" \
            "https://open.spotify.com/playlist/37i9dQZF1DX" "$(get URL_FROM_ID)"
  assert_eq "spotify_url leaves an album URL alone" \
            "https://open.spotify.com/album/1x2y" "$(get URL_KEPT)"
  assert_eq "spotify_id strips the query string"         "1x2y"   "$(get ID_FROM_URL)"
  assert_eq "slug is filesystem-safe"                    "90s_Rap_Best_Of" "$(get SLUG)"

  out="$(HOME="$home" MEGAPLAY_MUSIC="$music" bash "$proj/bin/status.sh" 2>&1)"
  if printf '%s' "$out" | grep -q 'Total songs on disk: 0'; then
    ok "status.sh runs against an empty library"
  else
    bad "status.sh runs against an empty library" "$out"
  fi

  # Nothing may be written outside the project tree. A script that quietly creates things in
  # someone's home directory is exactly what "installs nothing globally" promises it will not do.
  assert_empty "nothing was written outside the project tree" "$(find "$home" -mindepth 1 2>/dev/null)"

  # delete-playlist.sh builds an `rm -rf` out of its argument. An empty name expanded to
  # `rm -rf "$MUSIC/"` and took the whole library; set -u never caught it, because the
  # argument is present, just empty.
  local rc
  mkdir -p "$music/Keep Me"; : > "$music/Keep Me/song.mp3"
  HOME="$home" MEGAPLAY_MUSIC="$music" bash "$proj/bin/delete-playlist.sh" "" >/dev/null 2>&1; rc=$?
  if [ "$rc" -ne 0 ] && [ -f "$music/Keep Me/song.mp3" ]; then
    ok "delete-playlist.sh refuses an empty name and leaves the library alone"
  else
    bad "delete-playlist.sh refuses an empty name and leaves the library alone" \
        "exit was $rc and the library is $([ -f "$music/Keep Me/song.mp3" ] && echo intact || echo GONE)"
  fi
  HOME="$home" MEGAPLAY_MUSIC="$music" bash "$proj/bin/delete-playlist.sh" "../../etc" >/dev/null 2>&1; rc=$?
  if [ "$rc" -ne 0 ]; then ok "delete-playlist.sh refuses a path traversal"
  else bad "delete-playlist.sh refuses a path traversal" "exit was 0"; fi
}

# ---------------------------------------------------------------------------
# T4  the metadata pipeline, on audio generated here and never committed
# ---------------------------------------------------------------------------
t4_metadata() {
  group "T4  tagging, album collapse, dedupe"
  local py
  if ! command -v ffmpeg >/dev/null 2>&1; then
    skip "the whole metadata group" "no ffmpeg, so there is nothing to tag"; return
  fi
  if ! py="$(mutagen_python)"; then
    skip "the whole metadata group" "no python with mutagen; run setup.sh or apt install python3-mutagen"; return
  fi

  TMP="${TMP:-$(mktemp -d)}"
  local proj="$TMP/t4/proj" home="$TMP/t4/home" music="$TMP/t4/music" venv="$TMP/t4/venv"
  mkdir -p "$proj" "$home" "$music" "$venv/bin"
  cp -r bin "$proj/bin"; rm -f "$proj/bin/env.local.sh"; rm -rf "$proj/bin/__pycache__"
  # env.sh reaches mutagen through $SPOTDL_VENV/bin/python, so this stands one up rather than
  # requiring a 400 MB install. It must be a WRAPPER, never a symlink: a venv python invoked
  # through a symlink outside its own venv resolves sys.prefix to /usr and silently loses that
  # venv's site-packages, so mutagen_python() would verify the real path and the test would then
  # use a different interpreter. Harmless wherever the system python also carries mutagen, which
  # is why it passed everywhere except the one CI job that installs no python3-mutagen.
  printf '#!/bin/sh\nexec "%s" "$@"\n' "$py" > "$venv/bin/python"
  chmod +x "$venv/bin/python"

  local run=(env HOME="$home" MEGAPLAY_MUSIC="$music" SPOTDL_VENV="$venv" bash)

  mk() {  # mk <folder> <file> <title> <artist> <album>
    local dir="$music/$1"; mkdir -p "$dir"
    ffmpeg -loglevel quiet -y -f lavfi -i anullsrc=r=44100:cl=mono -t 1 -q:a 9 "$dir/$2" </dev/null
    TT="$3" TA="$4" TB="$5" "$py" - "$dir/$2" <<'PY'
import os, sys
from mutagen.mp3 import MP3
from mutagen.id3 import TIT2, TPE1, TALB, Encoding
a = MP3(sys.argv[1])
if a.tags is None: a.add_tags()
a.tags.setall("TIT2", [TIT2(encoding=Encoding.UTF8, text=[os.environ["TT"]])])
a.tags.setall("TPE1", [TPE1(encoding=Encoding.UTF8, text=[os.environ["TA"]])])
a.tags.setall("TALB", [TALB(encoding=Encoding.UTF8, text=[os.environ["TB"]])])
a.save()
PY
  }
  read_tag() {  # read_tag <path> <TIT2|TPE1|TALB>
    "$py" - "$1" "$2" <<'PY'
import sys
from mutagen.mp3 import MP3
a = MP3(sys.argv[1])
fr = a.tags.get(sys.argv[2]) if a.tags else None
print(", ".join(str(t) for t in fr.text) if fr else "")
PY
  }
  has_marker() {
    "$py" - "$1" <<'PY'
import sys
from mutagen.mp3 import MP3
a = MP3(sys.argv[1])
print("yes" if any(getattr(f, "desc", "") == "LOADOUT_TAGGED" for f in (a.tags.getall("TXXX") if a.tags else [])) else "no")
PY
  }

  mk "Parent/Sub"   "one.mp3"   "Song One"     "Real Artist" "Ready to Die (The Remaster)"
  mk "Parent/Sub"   "two.mp3"   "Song Two"     "Real Artist" "Ready to Die (The Remaster; 2015 Remaster)"
  mk "Parent/Other" "one.mp3"   "Song One"     "Real Artist" "Ready to Die"
  mk "Parent/Other" "three.mp3" "Song Three"   "Dr Dre"      "2001"
  mk "Parent/Other" "four.mp3"  "Song Four"    "Dr Dre"      "2001 (Explicit Version)"

  "${run[@]}" "$proj/bin/tag.sh" "Parent/Sub" >/dev/null 2>&1
  assert_eq "TITLE becomes '<title> - <artist>'" "Song One - Real Artist" \
            "$(read_tag "$music/Parent/Sub/one.mp3" TIT2)"
  assert_eq "ARTIST becomes the megaplaylist parent" "Parent" \
            "$(read_tag "$music/Parent/Sub/one.mp3" TPE1)"
  assert_eq "ALBUM is left untouched" "Ready to Die (The Remaster)" \
            "$(read_tag "$music/Parent/Sub/one.mp3" TALB)"
  assert_eq "the LOADOUT_TAGGED marker is stamped" "yes" "$(has_marker "$music/Parent/Sub/one.mp3")"

  # Idempotence is the property that keeps "Song One - Real Artist - Real Artist" from ever
  # appearing, and a re-run is routine: grab.sh tags after every download.
  "${run[@]}" "$proj/bin/tag.sh" "Parent/Sub" >/dev/null 2>&1
  assert_eq "a second tag pass never re-titles" "Song One - Real Artist" \
            "$(read_tag "$music/Parent/Sub/one.mp3" TIT2)"

  # Moving a folder under a different parent is fixed by re-tagging, so ARTIST is re-stamped
  # every run even on a marked file.
  mkdir -p "$music/Moved"; cp -r "$music/Parent/Sub" "$music/Moved/Sub"
  "${run[@]}" "$proj/bin/tag.sh" "Moved/Sub" >/dev/null 2>&1
  assert_eq "ARTIST is re-stamped after a move" "Moved" \
            "$(read_tag "$music/Moved/Sub/one.mp3" TPE1)"

  "${run[@]}" "$proj/bin/album-check.sh" "Parent" --apply >/dev/null 2>&1
  assert_eq "album spellings collapse onto the shortest name" "Ready to Die" \
            "$(read_tag "$music/Parent/Sub/two.mp3" TALB)"
  # An album can BE a year. Stripping years emptied the key for Dr. Dre's 2001 and the pair
  # went unreported until 2026-07-28.
  assert_eq "an album that is a year still collapses" "2001" \
            "$(read_tag "$music/Parent/Other/four.mp3" TALB)"

  # one.mp3 is in both Sub and Other, which is what overlapping sources produce.
  local out; out="$("${run[@]}" "$proj/bin/dedupe.sh" "Parent" 2>&1)"
  if printf '%s' "$out" | grep -qE '[1-9][0-9]* duplicated song'; then
    ok "dedupe.sh reports a cross-folder duplicate"
  else
    bad "dedupe.sh reports a cross-folder duplicate" "$out"
  fi
  if [ -f "$music/Parent/Sub/one.mp3" ] && [ -f "$music/Parent/Other/one.mp3" ]; then
    ok "dedupe.sh deletes nothing without --apply"
  else
    bad "dedupe.sh deletes nothing without --apply" "a report-mode run removed a file"
  fi
}

# ---------------------------------------------------------------------------
# T5  the five gesture clauses
# ---------------------------------------------------------------------------
t5_gesture() {
  group "T5  the five gesture clauses"
  if ! python3 -c 'import gi' >/dev/null 2>&1; then
    skip "the gesture clauses" "no python3-gi, which voice.py imports at module level"; return
  fi
  local out
  if out="$(python3 "$ROOT/tests/gesture_test.py" 2>&1)"; then
    printf '%s\n' "$out" | sed 's/^/  /'
    PASS=$((PASS+1))
  else
    bad "the gesture clauses" "$out"
  fi
}

# ---------------------------------------------------------------------------
# T6  the README still describes the code
# ---------------------------------------------------------------------------
t6_docs() {
  # Each side has one document that lists the commands, and it is a different document:
  # README.md is written for a downloader, CLAUDE.md for whoever works on this next. Same
  # check either way, which is why this group is not mirror-only.
  local doc; [ "$SIDE" = "private" ] && doc="CLAUDE.md" || doc="README.md"
  group "T6  docs match the code ($doc)"
  if [ ! -f "$doc" ]; then
    skip "docs match the code" "no $doc in this tree"; return
  fi
  # env.sh is sourced, never run; index-playlist.sh is called by more.sh rather than by hand.
  local exempt="env.sh index-playlist.sh"
  local f base missing="" phantom=""

  for f in bin/*.sh bin/voice.py; do
    base="$(basename "$f")"
    case " $exempt " in *" $base "*) continue;; esac
    grep -q "bin/$base" "$doc" || missing="$missing$base"$'\n'
  done
  assert_empty "every command is documented in $doc" "$missing" \
    "a command nobody can find is a command nobody runs"

  while read -r base; do
    [ -n "$base" ] || continue
    [ -e "$ROOT/$base" ] || phantom="$phantom$base"$'\n'
  done < <(grep -oE 'bin/[a-z-]+\.(sh|py)' "$doc" | sort -u)
  assert_empty "$doc names no command that does not exist" "$phantom"
}

# ---------------------------------------------------------------------------
# T7  the real library, private side only
#
# Not about the code: about the state the code has produced on this machine. Both checks are
# ones CLAUDE.md currently tells you to run by hand, which is the same as saying nobody runs
# them. Read-only, and it never touches the audio.
# ---------------------------------------------------------------------------
t7_library() {
  group "T7  library state"
  if [ "$SIDE" != "private" ]; then
    skip "library state" "public mirror, and there is no library here by design"; return
  fi
  local music="${MEGAPLAY_MUSIC:-$HOME/Music}"
  if [ ! -d "$music" ]; then
    skip "library state" "no library at $music"; return
  fi

  # The SD card is FAT32, so a name carrying any of ? * : < > | " \ downloads fine on ext4 and
  # then cannot be copied across. Hit on 2026-08-01 by an album whose real title ends in a
  # question mark. The fix is renaming the folder and its registry row; the ALBUM tag inside
  # each file keeps the real spelling, so the phone still displays it correctly.
  assert_empty "no FAT32-illegal characters in any name" \
    "$(find "$music" -regex '.*[?*:<>|"\\].*' 2>/dev/null)" \
    "rename the folder and its registry row, dropping the character"

  # grab.sh seeds these to stop spotdl re-fetching a song a sibling folder already holds, and
  # removes them in an EXIT trap. A leftover one silently blocks a legitimate re-download
  # later, and only kill -9 on grab.sh leaves them behind.
  assert_empty "no stale .mp3.skip files left by an interrupted grab" \
    "$(find "$music" -name '*.mp3.skip' 2>/dev/null)" \
    "delete them; a stale skip file blocks a re-download with no error"

  # Every registry row should have a folder. The reverse is not a fault: an empty megaplaylist
  # parent is a folder with no row on purpose, and status.sh reports those as empty.
  local missing="" name
  if [ -f "$ROOT/playlists.tsv" ]; then
    while IFS=$'\t' read -r name _rest; do
      [ "$name" = "name" ] || [ -z "$name" ] && continue
      [ -d "$music/$name" ] || missing="$missing$name"$'\n'
    done < "$ROOT/playlists.tsv"
    assert_empty "every registry row has a folder on disk" "$missing"
  else
    skip "every registry row has a folder on disk" "no playlists.tsv"
  fi
}

# ---------------------------------------------------------------------------

WANTED=("$@")
printf '%stest suite%s  (%s, %s side)\n' "$B" "$N" "$ROOT" "$SIDE"

want_group T1 && t1_lint
want_group T2 && t2_hygiene
want_group T3 && t3_fresh_clone
want_group T4 && t4_metadata
want_group T5 && t5_gesture
want_group T6 && t6_docs
want_group T7 && t7_library

printf '\n%s----- summary -----%s\n' "$B" "$N"
printf '  %s%s passed%s, %s%s failed%s, %s%s skipped%s\n' \
  "$G" "$PASS" "$N" "$([ "$FAIL" -gt 0 ] && printf '%s' "$R")" "$FAIL" "$N" \
  "$([ "$SKIPPED" -gt 0 ] && printf '%s' "$Y")" "$SKIPPED" "$N"

# A skip is reported at the end as well as inline, because a suite that scrolls past its own
# gaps is how "all green" comes to mean "I could not look".
if [ "$SKIPPED" -gt 0 ]; then
  printf '\n  not checked on this machine:\n'
  printf '    %s\n' "${SKIPPED_NAMES[@]}"
fi
if [ "$FAIL" -gt 0 ]; then
  printf '\n  %sfailed:%s\n' "$R" "$N"
  printf '    %s\n' "${FAILED_NAMES[@]}"
  exit 1
fi
exit 0
